apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service # {"$kpt-set":"name"}
  # namespace: project-two # {"$kpt-set":"namespace"}
spec:
  replicas: 1 # {"$kpt-set":"replicas"}
  selector:
    matchLabels:
      app: web-service # {"$kpt-set":"name"}
      version: v1
  template:
    metadata:
      labels:
        app: web-service # {"$kpt-set":"name"}
        version: v1
    spec:
      serviceAccountName: web-service # {"$kpt-set":"name"}
      containers:
      - image: docker.io/kennethreitz/httpbin # {"$kpt-set":"image"}
        imagePullPolicy: IfNotPresent
        name: web-service # {"$kpt-set":"name"}
        ports:
        - containerPort: 80 # {"$kpt-set":"container-port"}
