apiVersion: v1
kind: Service
metadata:
  name: web-service # {"$kpt-set":"name"}
  namespace: project-two # {"$kpt-set":"namespace"}
  labels:
    app: web-service # {"$kpt-set":"name"}
    service: web-service # {"$kpt-set":"name"}
spec:
  ports:
  - name: http
    port: 8000 # {"$kpt-set":"port"}
    targetPort: __container-port__ # {"$kpt-set":"container-port"}
  selector:
    app: web-service # {"$kpt-set":"name"}
